# Generated by Django 5.2.13 on 2026-05-18 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='current_turn_team',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='current_turn_word',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
