# Generated by Django 5.2.13 on 2026-05-19 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_card_flipped_by_alter_card_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playergame',
            name='role',
            field=models.CharField(choices=[('associator', 'Ассоциатор'), ('disassociator', 'Десоциатор'), ('none', 'Нет роли')], max_length=15),
        ),
    ]
