# Generated by Django 5.2.13 on 2026-05-20 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_playergame_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='turn_phase',
            field=models.CharField(choices=[('hint', 'Ассоциатор дает подсказку'), ('guess', 'Десоциаторы угадывают')], default='hint', max_length=10),
        ),
    ]
