# Generated by Django 5.2.13 on 2026-05-30 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_game_turn_phase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playergame',
            name='score',
        ),
        migrations.AddField(
            model_name='game',
            name='blue_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='red_score',
            field=models.IntegerField(default=0),
        ),
    ]
