# Generated by Django 5.2.13 on 2026-05-30 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_playergame_score_game_blue_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playergame',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
