# Generated by Django 5.2.13 on 2026-05-30 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_playergame_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='color',
            field=models.CharField(choices=[('blue', 'Blue'), ('red', 'Red'), ('black', 'Black'), ('unknown', 'Unknown')], max_length=10),
        ),
    ]
