# Generated by Django 5.2.13 on 2026-05-30 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_card_color'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hint',
        ),
    ]
